# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-FormValidator-Simple
version:      0.04
version_from: lib/Catalyst/Plugin/FormValidator/Simple.pm
installdirs:  site
requires:
    Catalyst:                      5.3
    Catalyst::Plugin::FormValidator: 0
    FormValidator::Simple:         0.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
